### ISSUE TITLE
Sort exports alphabetically

### ISSUE THREAD

**Issue by emersonsiega** [pastordougdev/dart-barrel-file#1]
I'm using this plugin in a project with a linter rule that requests to always sort exported classes alphabetically.

I think this is a good practice that could be followed by this plugin :)

**Comment by pastordougdev** [comment]
Thank you for your feedback.  I have submitted version 0.3.0 to the Marketplace for this.  The export statements will be written alphabetically based upon the *.dart file name.  If you require another type of sort, please provide an example and I will be happy to review.

You can use the Refresh Barrel File action to apply the sorting to previous generated barrel files.
