### ISSUE TITLE
Barrel files not being generated as expected

### ISSUE THREAD

**Issue by emersonsiega** [pastordougdev/dart-barrel-file#2]
There's a behavior on barrel file generation that I believe it's wrong and/or can be improved...

Look this example. My directory is:
```
/loans
    /viewmodel
    /widgets
```

Using option "Dart barrel file with subdirectories" **I expect to generate 3 files:** 
`loans/viewmodel/viewmodel.dart`, `loans/widgets/widgets.dart` and `loans/loans.dart`. 

- `viewmodel.dart` should export everything inside `/loans/viewmodel`
- `widgets.dart` should export everything inside `/loans/widgets` and 
- `loans/loans.dart` should export the barrel files inside the subdirectories. In that case, it's content should be:
```dart
export 'viewmodel/viewmodel.dart';
export 'widgets/widgets.dart';
```

This is what happens:
- /loans directory selected with  "Dart barrel file with subdirectories":
![image](https://user-images.githubusercontent.com/2227499/173139297-348ee0ba-5c9d-4e29-bd73-eecdad9ab211.png)

- Select all files/subdirectories and press ok:
![image](https://user-images.githubusercontent.com/2227499/173138554-3e2e5935-9766-4b15-86d2-e8f9d7541e63.png)

- All barrel files kept untouched and no errors was shown.
![image](https://user-images.githubusercontent.com/2227499/173138619-eb6a0bed-7786-4698-8b92-2d6240b1f95e.png). 

I was using VSCode for a while, and was using [this plugin](https://marketplace.visualstudio.com/items?itemName=miquelddg.dart-barrel-file-generator). It works like I said above...

I think this could be a great feature to add to this plugin :)

**Comment by pastordougdev** [comment]
Thank you for your feedback.  I use the plugin to achieve the same type of result you are going for.  When creating the loans.dart barrel file, you have to just select the two lower barrel files in the dialog box to get your desired results.  

I have been thinking this behavior was confusing but have been living with it.  Based on your feedback, I'm going to address this.  I think the solution would be to exclude the lower level files if they have already been added to a barrel file.

**Comment by pastordougdev** [comment]
Release 0.4.0 has been submitted to the plugins marketplace to address this.  Thank you!
