### ISSUE TITLE
IntelliJ Freezes when using "Dart Barrel File With Subdirectories"

### ISSUE THREAD

**Issue by ltoenjes** [pastordougdev/dart-barrel-file#3]
The IDE is completely unresponsive and has to be terminated via Activity Monitor after selecting that option. I checked the logs and couldn't find anything hinting at the issue...

I'm running IntelliJ Ultimate (222.4345.14) on macOS Ventura 13.0.

**Comment by tenhobi** [comment]
I face the same issue with Android Studio on Windows 11.

> Android Studio Flamingo | 2022.2.1 Canary 8
> Build #AI-222.4345.14.2221.9252092, built on November 3, 2022
> Runtime version: 17.0.4.1+0-b2043.56-9127311 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by pastordougdev** [comment]
Hi @ltoenjes and @tenhobi , I am going to investigate this.  Thanks for reporting the problem.

**Comment by pastordougdev** [comment]
Hi @ltoenjes  and @tenhobi - I've had another report of this error. However, I have not been able to recreate the error. Could you send me some information about your project where you got this error? Specifically, could you let me know the directory structure of your project where you got this error?

**Comment by tenhobi** [comment]
Hello @pastordougdev. I tried to test the issue in the project and even in a new one. In the meantime, I updated version 0.5.0 (from Nov 15, 2022). And the issue no longer appears, or I cannot reproduce that at least. I don't know what the changes in that version are.

**Comment by tenhobi** [comment]
Lol, that being said I found an issue just at the time I posted the comment. :D 

For this structure
![image](https://user-images.githubusercontent.com/5287596/202921874-feef3369-c40b-4b48-a46a-8b627ffe97e4.png)

All the directories (and action barrel file w/ subdirectories) works for everything except the `uhh` directory.

**Comment by pastordougdev** [comment]
@tenhobi , thank you for your reply.  This helped me track down where the issue was occurring.  I have just uploaded an update (v0.5.1).  It usually takes a day or two for Jetbrains to approve and release to the market place.
