### ISSUE TITLE
Generate barrel file syntax error

### ISSUE THREAD

**Issue by tenhobi** [pastordougdev/dart-barrel-file#4]
In Android Studio on WInapparentdows 11 I face issues with generating barrel files. When I have the "old" barrel file open, I see it generates this:

![image](https://user-images.githubusercontent.com/5287596/201917244-364168a0-1bd6-462c-9b76-6052fde593dd.png)

But on auto save (but not on code format, that works ok), it ends up like this:

![image](https://user-images.githubusercontent.com/5287596/201917538-07c4771b-e0ee-468a-90dd-f4abe8e20f67.png)

> Android Studio Flamingo | 2022.2.1 Canary 8
> Build #AI-222.4345.14.2221.9252092, built on November 3, 2022
> Runtime version: 17.0.4.1+0-b2043.56-9127311 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by pastordougdev** [comment]
Hi @tenhobi , did this happen when you where adding another export to an already existing barrel file?

**Comment by tenhobi** [comment]
It seems that it only affects already created barrel files.

**Comment by pastordougdev** [comment]
@tenhobi , can you see if this problem recreates on the newest 0.5.1 release?

**Comment by tenhobi** [comment]
@pastordougdev tried on use case with 0.5.0, which froze. After that, I upgraded and tried that again multiple times, and it didn't freeze. So hopefully, it's fixed. Yay!
