### ISSUE TITLE
Incompatibility with new IntelliJ UI

### ISSUE THREAD

**Issue by emersonsiega** [pastordougdev/dart-barrel-file#5]
Please, could you solve this incompatibility?
(To simulate, just upgrade your IDE and activate the new UI in the IntelliJ settings)

![image](https://user-images.githubusercontent.com/2227499/216793218-9ba7de91-bbfd-4e0d-93df-aa4ff70996ea.png)

Thanks!!!

**Comment by pastordougdev** [comment]
An update has been submitted to the Market Place.  It should be available within a day or two.  Thank you for your patience.

**Comment by pastordougdev** [comment]
The 0.5.2 update is available in the market place for this issue.
