### ISSUE TITLE
Import sorting

### ISSUE THREAD

**Issue by oravecz** [pastordougdev/dart-barrel-file#6]
One of the Dart analyzer's we have turned on (based on Very Good Design analyzer rules), is a check to ensure the imports in a file are sorted. It becomes very cumbersome to generate or regenerate a barrel file, only to load the file and sort the rows.

Could you make this the default behavior in this plugin, or at least allow it to be a setting? 

Another approach (not recommended by me because it is a lot slower) would be to execute `dart fix --apply <barrel_file>`

**Comment by pastordougdev** [comment]
Hi @oravecz ,

In the 0.3.0 release, I implemented some sorting of the generated barrel file.  However, I believe it is only considering the *.dart file name in the sorting.  Perhaps that needs to be expanded a bit more.  

Do you have an example of a generated barrel file that needed to resorted for your analyzer rule?  I will be happy to work on making a change that fits this need.

**Comment by oravecz** [comment]
Here are the rules for the `directives_ordering` lint
https://dart-lang.github.io/linter/lints/directives_ordering.html

> Note: they actually have sections separated by a blank line

1. Place `dart:` imports before other imports (not really part of a generated barrel, unless you respect code in the barrel that is there already (e.g. like a custom import/export clause)
2. Place `package:` imports before relative imports (not really part of a generated barrel...)
3. Specify exports in a separate section after all imports
4. Sort sections alphabetically

**Comment by pastordougdev** [comment]
I enabled the directives_ordering lint rule and was able to change the sorting to satisfy this line rule.  I am submitted an update to the Market Place right now.

Thanks for your feedback!

**Comment by oravecz** [comment]
Thanks for the fast turnaround

**Comment by pastordougdev** [comment]
My pleasure!  The 0.5.3 version is now available on the marketplace.  If you have any more issues, please let me know.
